USE lprs;

DELETE FROM REWARDTRANSACTION WHERE Transaction_ID=300;
DELETE FROM REWARDTRANSACTION WHERE Transaction_ID=301;
DELETE FROM REWARDTRANSACTION WHERE Transaction_ID=302;
DELETE FROM REWARDTRANSACTION WHERE Transaction_ID=303;

DELETE FROM PERCENTDISCOUNTREWARD WHERE Reward_ID=200;
DELETE FROM PRICEDISCOUNTREWARD WHERE Reward_ID=201;
DELETE FROM PRODUCTUPGRADEREWARD WHERE Reward_ID=202;
DELETE FROM EXCLUSIVEPRODUCTREWARD WHERE Reward_ID=203;

DELETE FROM REWARDS WHERE Reward_ID=200;
DELETE FROM REWARDS WHERE Reward_ID=201;
DELETE FROM REWARDS WHERE Reward_ID=202;
DELETE FROM REWARDS WHERE Reward_ID=203;

DELETE FROM PRODUCTS WHERE Product_ID=100;
DELETE FROM PRODUCTS WHERE Product_ID=101;
DELETE FROM PRODUCTS WHERE Product_ID=102;

DELETE FROM USERS WHERE User_ID=1;
