USE lprs;

DROP TABLE IF EXISTS REWARDTRANSACTION;
DROP TABLE IF EXISTS PERCENTDISCOUNTREWARD;
DROP TABLE IF EXISTS PRICEDISCOUNTREWARD;
DROP TABLE IF EXISTS PRODUCTUPGRADEREWARD;
DROP TABLE IF EXISTS EXCLUSIVEPRODUCTREWARD;
DROP TABLE IF EXISTS REWARDS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS USERS;
