USE lprs;

DROP TABLE IF EXISTS PERCENTDISCOUNTREWARDVIEW;
DROP TABLE IF EXISTS PRICEDISCOUNTREWARDVIEW;
DROP TABLE IF EXISTS PRODUCTUPGRADEREWARDVIEW;
DROP TABLE IF EXISTS EXCLUSIVEPRODUCTREWARDVIEW;
