USE lprs;

DROP VIEW IF EXISTS PERCENTDISCOUNTREWARDVIEW;
DROP VIEW IF EXISTS PRICEDISCOUNTREWARDVIEW;
DROP VIEW IF EXISTS PRODUCTUPGRADEREWARDVIEW;
DROP VIEW IF EXISTS EXCLUSIVEPRODUCTREWARDVIEW;
Drop VIEW IF EXISTS REWARDTRANSACTIONVIEW;